version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      parser-dependencies:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /web/backend
    schedule:
      interval: monthly
    groups:
      backend-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /web/frontend
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      frontend-dependencies:
        patterns: ["*"]
